Implements Mailing System with Handlebars Templates
ifpeopensource/merenda-server pull request #20
Opened 2023-02-21 20:33 UTC by Gvinfinity

- Resolves #19 
- Fix bug with qrcode generation

2023-02-21 23:03 UTC, weltonfelix requested changes
Além de algumas correções e dúvidas pelo código, precisamos reestruturar as pastas por conta da adição do nodemailer-express-handlebars.

O nodemailer-express-handlebars utiliza `views`, `layouts` e `partials`. De acordo com a [documentação](https://github.com/yads/nodemailer-express-handlebars), as `views` são os conteúdos dos e-mails em si, as `partials` são componentes reutilizáveis entre as views e os `layouts` são estruturas html padrões para serem reutilizadas em várias views.

Por isso, sugiro que dentro da pasta `emails` seja criada uma pasta `messages` e as funções de envio de e-mails sejam movidas para lá, para não ficarem na mesma pasta das views do handlebars, e que as views (que atualmente estão na pasta layouts) sejam movidas para a pasta `views`.

O arquivo `email.handlebars` pode ser renomeado para `studentQRCodeEmail.handlebars`, para ficar mais descritivo.

Já na view em si, sugiro que seja adicionado um `border-radius` ao QR Code e que seja adicionado um link para o site do IFPE Open Source na mensagem no rodapé do e-mail.

2023-02-21 23:03 UTC, weltonfelix commented on src/utils/generateStudentQRCode.js
>  export async function generateStudentQRCode(studentId, base64Image) {
Nessa função estão sendo utilizadas vários valores para a estilização.
Como esses valores são constantes, podemos colocá-los fora da função:
Ex.:
```js
const QR_CODE_OPTIONS = {
  errorCorrectionLevel: 'H',
  // ...
};

const BASE_64_IMAGE_SCALE_FACTOR = {
  width: 0.245,
  // ...
};

const QR_CODE_COLORS = {
  background: '#FFFFFF',
  foreground: '#AAAAAA',
  // ...
};

const QR_CODE_DETAILS = {
  square: {
    backgroundColor: '#FF0000',
    scaleFactor: {
      width: 0.5,
      //...
    },
    //...
  },
  //...
};
```

2023-02-21 23:03 UTC, weltonfelix commented on src/infra/email/nodemailer.js
> +dotenv.config();
O dotenv já é configurado no entrypoint da aplicação (`server.js`).

```suggestion

```

2023-02-21 23:03 UTC, weltonfelix commented on src/infra/email/nodemailer.js
> +const handlebarOptions = {
Nomear constante com snake case all caps e colocá-la logo após as importações.

```suggestion
const HANDLEBARS_OPTIONS = {
```

2023-02-21 23:03 UTC, weltonfelix commented on src/infra/email/nodemailer.js
> +  ignoreTLS: true,
Verificar configurações de segurança.

2023-02-21 23:03 UTC, weltonfelix commented on src/infra/email/nodemailer.js
> +    defaultLayout: false,
Essa opção realmente precisa ser passada como false?

2023-02-21 23:03 UTC, weltonfelix commented on src/infra/email/nodemailer.js
> +    partialDirs: path.resolve('./src/infra/email/views/layouts'),
As partials não devem ser os layouts. De acordo com a [documentação do handlebars](https://handlebarsjs.com/guide/partials.html#basic-partials), partials são componentes reutilizados em diversos layouts.

2023-02-21 23:03 UTC, weltonfelix commented on src/infra/email/nodemailer.js
> +  viewPath: path.resolve('./src/infra/email/views/layouts'),
Utilizar `__dirname` ao invés de path absoluto.

2023-02-21 23:03 UTC, weltonfelix commented on src/infra/email/nodemailer.js
>      if (error) {
Remover mensagem de email enviado. Padronizar mensagem de erro em inglês e utilizar `console.error()` ao invés de `console.log`.

2023-02-21 23:03 UTC, weltonfelix commented on src/infra/email/views/sendStudentQRCodeEmail.js
>    await mailing.sendEmail(message);
Essa função pode disparar um erro. Utilizar um try.

2023-02-21 23:03 UTC, weltonfelix commented on src/infra/email/views/layouts/email.handlebars
> +    <title>Email QRCode</title>
Remover tag title.

2023-02-21 23:03 UTC, weltonfelix commented on src/infra/email/views/layouts/email.handlebars
> +    <meta charset="utf-8">
Melhorar suporte.
```suggestion
        <meta http-equiv="Content-Type" content="text/html charset=UTF-8" />
```

2023-02-21 23:03 UTC, weltonfelix commented on src/infra/email/views/layouts/email.handlebars
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0">
Tag não necessária em e-mails, removê-la

2023-02-21 23:03 UTC, weltonfelix commented on src/infra/email/views/layouts/email.handlebars
> +    </style>
Corrigir identação.

2023-02-21 23:34 UTC, weltonfelix commented on src/infra/email/views/sendStudentQRCodeEmail.js
>      subject: 'QRCode',
Modificar título do e-mail para algo mais user friendly.

```suggestion
    subject: 'Aqui está seu QR Code para receber a merenda!',
```

2023-02-22 00:05 UTC, Gvinfinity commented on src/infra/email/nodemailer.js
> +    defaultLayout: false,
Sim! Pela falta de utilização de layout para construção da view, é necessário especificar.

2023-02-22 03:00 UTC, weltonfelix approved these changes

2023-02-22 03:03 UTC, merged