Envio de E-mail
ifpeopensource/merenda-server pull request #6
Opened 2023-02-16 19:31 UTC by carvalhoedsonn

Gerador de QRCode e Envio de Email contendo o QRCode gerado ✔️

2023-02-16 19:34 UTC, Gvinfinity commented
Implementação de #4

2023-02-16 22:04 UTC, weltonfelix requested changes
Muito bom! Algumas mudanças na lógica e no estilo são necessárias.

2023-02-16 22:04 UTC, weltonfelix commented on src/controllers/UserController.js
> -    const users = await UserService.findAll();
Alterar este controller não está no escopo dessa PR. Reverter a exclusão dessa linha.

2023-02-16 22:04 UTC, weltonfelix commented on src/infra/nodemailer/setup.js
> +dotenv.config();
Segundo a [documentação](https://github.com/motdotla/dotenv#usage) da lib dotenv, a configuração dela deve ser feita logo no início da execução da aplicação, para que as variáveis ambiente sejam importadas cedo.

Ou seja, seria melhor importar a lib e executar o `dotenv.config` nas primeiras linhas do `server.js`.

ex.:
```js
import * as dotenv from 'dotenv';
dotenv.config();

import express from 'express';
import cors from 'cors';

import routes from './routes.js';

2023-02-16 22:04 UTC, weltonfelix commented on src/infra/nodemailer/setup.js
> +import { generatingQRCode } from '../../utils/generateQRCode.js';
Adicionar uma linha em branco entre as importações de biblioteca e as importações de arquivos do projeto.
```suggestion

import { generatingQRCode } from '../../utils/generateQRCode.js';
```

2023-02-16 22:04 UTC, weltonfelix commented on src/infra/nodemailer/setup.js
> +    pass: process.env.email_pass
Como as variáveis ambientes são constantes, é convenção nomeá-las em snake case com todas as letras maiúsculas:

ex.: EMAIL_HOST, EMAIL_PORT...

2023-02-16 22:04 UTC, weltonfelix commented on src/infra/nodemailer/setup.js
> +let transporter = nodemailer.createTransport({
Como a `transporter` nunca muda, ela poderia ser inicializada como uma const.
```suggestion
const transporter = nodemailer.createTransport({
```

2023-02-16 22:04 UTC, weltonfelix commented on src/infra/nodemailer/setup.js
> +  var message = {
Como `message` nunca muda, pode ser inicializada como const. Obs.: Evitar utilizar var pois pode causar problemas com escopos.

```suggestion
  const message = {
```

2023-02-16 22:04 UTC, weltonfelix commented on src/infra/nodemailer/setup.js
> +      cid: 'qr-code-cid'
Seguindo a [documentação](https://nodemailer.com/message/embedded-images/) do nodemailer, seria interessante colocar o CID em um formato padronizado.

```suggestion
    html: `<p>Este é o seu QRCode de acesso:</p><img src="cid:student_qr_code@ifpeopensource.com.br" alt="QR code">`,
    attachments: [{
      filename: 'qrcode.png',
      path: `${QRCode}`,
      cid: 'student_qr_code@ifpeopensource.com.br'
```

Provavelmente seria melhor colocar o host do e-mail ao invés de `@ifpeopensource.com.br` hardcoded.

2023-02-16 22:04 UTC, weltonfelix commented on src/infra/nodemailer/setup.js
> +    } else {
O que acha de fazer o throw do erro caso o e-mail não possa ser enviado para permitir o tratamento dele nas camadas superiores?

2023-02-16 22:04 UTC, weltonfelix commented on src/infra/nodemailer/setup.js
> +}
Adicionar uma linha em branco ao final do arquivo por questões de estilo.

```suggestion
}

```

2023-02-16 22:04 UTC, weltonfelix commented on src/server.js
> +import { sendEmail } from './infra/nodemailer/setup.js'; // Importando a função do setup.js
Essa função não deve ser chamada aqui. Sugiro remover essas alterações do `server.js` e deixá-las a cargo dos responsáveis pela issue do CRUD (#1) ou da automatização do cadastro de estudantes (#5).

2023-02-16 22:04 UTC, weltonfelix commented on src/utils/generateQRCode.js
> +export async function generatingQRCode() {
Por convenção, nomes de funções devem ser verbos no presente simples. Esta aqui poderia ser renomeada.

Além disso, o QRCode deverá ser gerado com base no número de matrícula do estudante (`studentId`) e não em uma string aleatória.

```suggestion
export async function generateStudentQRCode(studentId) {
```

2023-02-16 22:04 UTC, weltonfelix commented on src/utils/generateQRCode.js
> +    const code = crypto.randomBytes(8).toString('hex');
```suggestion
```

2023-02-16 22:04 UTC, weltonfelix commented on src/utils/generateQRCode.js
> +import crypto from 'crypto';
```suggestion
```

2023-02-16 22:04 UTC, weltonfelix commented on src/utils/generateQRCode.js
> +    const qrCode = await qrcode.toDataURL(code,  {
```suggestion
    const qrCode = await qrcode.toDataURL(studentId,  { 
```

2023-02-16 22:07 UTC, carvalhoedsonn commented on src/controllers/UserController.js
> -    const users = await UserService.findAll();
Certo

2023-02-16 22:07 UTC, carvalhoedsonn commented on src/infra/nodemailer/setup.js
> +dotenv.config();
Certo

2023-02-16 22:07 UTC, carvalhoedsonn commented on src/infra/nodemailer/setup.js
> +import { generatingQRCode } from '../../utils/generateQRCode.js';
Certo

2023-02-16 22:08 UTC, carvalhoedsonn commented on src/infra/nodemailer/setup.js
> +    pass: process.env.email_pass
Certo, desta forma:
process.env.EMAIL_HOST?
process.env.EMAIL_USER?

2023-02-16 22:09 UTC, carvalhoedsonn commented on src/infra/nodemailer/setup.js
> +let transporter = nodemailer.createTransport({
Certo, fiz assim, pois foi sugestão da propia docs.

2023-02-16 22:09 UTC, weltonfelix commented on src/infra/nodemailer/setup.js
> +    pass: process.env.email_pass
Isso!

2023-02-16 22:09 UTC, carvalhoedsonn commented on src/infra/nodemailer/setup.js
> +  var message = {
Certo
Tinha feito como tu falou lá sakdhaskd, mas tudo bem

2023-02-16 22:11 UTC, carvalhoedsonn commented on src/infra/nodemailer/setup.js
> +      cid: 'qr-code-cid'
Certo.

2023-02-16 22:11 UTC, weltonfelix commented
Outra coisa que esqueci de comentar. Para facilitar os outros desenvolvedores saberem quais são as variáveis ambiente que o projeto usa, adicione as que você criou no modelo `.env.template`.

2023-02-16 22:13 UTC, carvalhoedsonn commented on src/infra/nodemailer/setup.js
> +    } else {
Boa ideia, irei fazer.

2023-02-16 22:14 UTC, carvalhoedsonn commented on src/infra/nodemailer/setup.js
> +}
Certo.

2023-02-16 22:14 UTC, carvalhoedsonn commented on src/server.js
> +import { sendEmail } from './infra/nodemailer/setup.js'; // Importando a função do setup.js
Sim, foi chamada apenas em função de testes.

2023-02-16 22:16 UTC, carvalhoedsonn commented on src/utils/generateQRCode.js
> +export async function generatingQRCode() {
Sim, eu disse isso para o GV, mas como ele irá criar um token propio e não será usado apenas o número de matrícula, então avisei a ele que iria deixar sim

2023-02-16 22:42 UTC, weltonfelix requested changes
Verificar mudanças solicitadas anteriormente.

2023-02-16 22:42 UTC, weltonfelix commented on .env.template
> +EMAIL_PORT=
Adicionar linha em branco ao final do arquivo.
```suggestion
EMAIL_PORT=

```

2023-02-16 22:42 UTC, weltonfelix commented on src/utils/generateQRCode.js
> +export async function generatingQRCode() {
Acho que você esqueceu de renomear a função

2023-02-16 22:43 UTC, weltonfelix commented on src/infra/nodemailer/setup.js
> +dotenv.config();
Faltou levar essa configuração pro `server.js`.

2023-02-17 00:05 UTC, weltonfelix approved these changes, later dismissed

2023-02-17 01:13 UTC, Gvinfinity requested changes
Tudo certinho, só umas mudanças pra entrar no padrão do repositório:

- Mudar o caminho para o arquivo de `src/infra/nodemailer/setup.js` para `src/services/MailService.js`
- Mudar a forma de exportação para que a função seja exportada no final: 
   `export default { sendEmail }`

2023-02-17 01:45 UTC, carvalhoedsonn commented
> Tudo certinho, só umas mudanças pra entrar no padrão do repositório:
> 
> * Mudar o caminho para o arquivo de `src/infra/nodemailer/setup.js` para `src/services/MailService.js`
> * Mudar a forma de exportação para que a função seja exportada no final:
>   `export default { sendEmail }`

2023-02-17 02:07 UTC, Gvinfinity approved these changes
Simbora :rocket:

2023-02-17 02:09 UTC, weltonfelix approved these changes

2023-02-17 02:09 UTC, merged