Função sendEmail refatorada para reutilização e função de enviar qrcode por e-mail criada.
ifpeopensource/merenda-server pull request #9
Opened 2023-02-18 00:53 UTC by carvalhoedsonn

Resumo:

O sendEmail está recebendo dois parametros, message e studentData.
Message será um objeto que irá conter as informações obrigatórias para enviar o e-mail, como from, to, etc.
studentData será um objeto que irá conter os dados do estudante.

No finalzinho a função sendMail é chamada passando o objeto message como parâmetro.

2023-02-18 02:22 UTC, Gvinfinity requested changes
Algumas correções de erros e sugestões de melhoria.

2023-02-18 02:22 UTC, Gvinfinity commented on src/infra/email/views/sendStudentQRCodeEmail.js
> +import sendEmail from '../nodemailer.js';
Pela forma de exportação em `nodemailer.js`, aqui deve ser `import NodeMailer from '../nodemailer.js'`.

2023-02-18 02:22 UTC, Gvinfinity commented on src/infra/email/views/sendStudentQRCodeEmail.js
> +  await sendEmail(message);
Considerando a importação de antes, aqui deveria ser `await NodeMailer.sendEmail(message)`.

2023-02-18 02:22 UTC, Gvinfinity commented on src/infra/email/views/sendStudentQRCodeEmail.js
> +  const QRCode = await generateStudentQRCode();
Chamada para a função sem os parametros necessários, deveria ser:
`const QRCode = await generateStudentQRCode(studentData.id);`

2023-02-18 02:22 UTC, Gvinfinity commented on src/infra/email/views/sendStudentQRCodeEmail.js
> +        filename: 'qrcode.png',
Alterar o filename para o padrão "Nome - MATRICULA.png".

2023-02-19 01:06 UTC, Gvinfinity requested changes

2023-02-19 01:06 UTC, Gvinfinity commented on src/utils/generateStudentQRCode.js
> +
Mudar para Promise.all()

2023-02-19 01:13 UTC, Gvinfinity approved these changes, later dismissed

2023-02-19 01:37 UTC, weltonfelix requested changes
Algumas melhorias na estrutura do código.

2023-02-19 01:37 UTC, weltonfelix commented on src/utils/generateStudentQRCode.js
> +  const centerY = qrCodeOptions.width / 2;
Agrupar variavéis em uma só.

```suggestion
  const centerCoords = {
    x: qrCodeOptions.width / 2,
    y: qrCodeOptions.width / 2
  };
```

2023-02-19 01:37 UTC, weltonfelix commented on src/utils/generateStudentQRCode.js
> +  const rectangleY = centerY - rectangleHeight / 2;
```suggestion
  const rectangleCoords = {
    width: base64ImageDimensions.width * 1.0,
    height: base64ImageDimensions.height * 1.0,
    x: centerCoords.x - (base64ImageDimensions.width * 1.0) / 2,
    y: centerCoords.y - (base64ImageDimensions.height * 1.0) / 2,
  };
```

2023-02-19 01:37 UTC, weltonfelix commented on src/utils/generateStudentQRCode.js
> +    rectangleY + (rectangleHeight - base64ImageDimensions.height) / 2,
```suggestion
    rectangleCoords.x + (rectangleCoords.width - base64ImageDimensions.width) / 2,
    rectangleCoords.y + (rectangleCoords.height - base64ImageDimensions.height) / 2,
```

2023-02-19 01:37 UTC, weltonfelix commented on src/infra/email/views/sendStudentQRCodeEmail.js
> +import NodeMailer from '../nodemailer.js';
Como esse arquivo é agnóstico de biblioteca, seria interessante nomear de forma mais genérica a importação (ainda que ela seja importada do setup da lib). Também seria legal deixar minúsculo, por padronização.
```suggestion
import mailing from '../nodemailer.js';
```

2023-02-19 01:37 UTC, weltonfelix commented on src/infra/email/views/sendStudentQRCodeEmail.js
> +    'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAMgAAADICAYAAACtWK6eAAAPrklEQVR4nOzde5QT130H8DsajaSVRtKutLCPAMEku/h57CUurh/FJ9g4TvGJHxBDcmLHrreu82yIG2hjc2q7tZ3gxjGHFk7Low22yyN2DQ04djC22dhx6gBLXBx2
Como o base64 é uma string muito grande, para não poluir o arquivo, sugiro criar uma pasta `assets` dentro de src e exportar essa string de um arquivo como `IFOSBase64Logo.ts`. Assim, também fica claro que o base64 se trata da logo do IFPE Open Soure e evita essa constante mágica.

2023-02-19 01:37 UTC, weltonfelix commented on src/infra/email/views/sendStudentQRCodeEmail.js
> +  await NodeMailer.sendEmail(message);
```suggestion
  await mailing.sendEmail(message);
```

2023-02-19 02:15 UTC, Gvinfinity submitted a review, later dismissed

2023-02-19 02:41 UTC, weltonfelix requested changes
Acho que você esqueceu de atualizar os parâmetros após a mudança nas variáveis.

2023-02-19 02:41 UTC, weltonfelix commented on src/utils/generateStudentQRCode.js
> +  context.fillRect(rectangleX, rectangleY, rectangleWidth, rectangleHeight);
Atualizar variáveis após mudanças

2023-02-19 02:41 UTC, weltonfelix requested changes
Acho que você esqueceu de atualizar os parâmetros após a mudança nas variáveis.

2023-02-19 02:48 UTC, weltonfelix approved these changes
Vamo lá!! :rocket:

2023-02-19 02:53 UTC, merged